{% set name = "block_diag_ilu" %}
{% set version = "0.4.0.dev0+git" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  number: 200
  features:
    - blas_{{ variant }}  # [not win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
    - cython
    - pip
    - libblas
    - liblapack
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pytest
    - scipy
  imports:
    - block_diag_ilu

about:
  home: https://github.com/chemreac/{{ name }}
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Incomplete LU factorization of block diagonal matrices with weak sub-/super-diagonals.'


extra:
  recipe-maintainers:
    - bjodah
